import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { validateRequest } from "@/lib/auth/validate-request";
import QueryProvider from "@/components/provider/query-provider";
import LeftSidebar from "./_components/sidebar/left/left-sidebar";
import { ThemeProvider } from "@/components/provider/theme-provider";
import SessionProvider from "@/components/provider/session-provider";
import ProgressbarProvider from "@/components/provider/progressbar-provider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
  referrer: "no-referrer",
  icons: [
    {
      url: "/assets/favicon.png",
      href: "/assets/favicon.png",
    },
  ],
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const session = await validateRequest();
  const { user } = session;

  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      suppressContentEditableWarning={true}
    >
      <body className={cn(inter.className, "antialiased min-h-screen w-full")}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <QueryProvider>
            <SessionProvider session={session}>
              <ProgressbarProvider>
                <div className="flex justify-between w-full">
                  <div className="h-full hidden md:flex w-[244px] max-[1263px]:w-[72px] 3xl:w-[336px]">
                    <LeftSidebar user={user!} />
                  </div>
                  <div className="flex-1 w-full">
                    {children}
                    {modal}
                    <div id="modal-root" />
                  </div>
                </div>
              </ProgressbarProvider>
            </SessionProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
