import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { validateRequest } from "@/lib/auth/validate-request";
import QueryProvider from "@/components/provider/query-provider";
import LeftSidebar from "./_components/sidebar/left/left-sidebar";
import { ThemeProvider } from "@/components/provider/theme-provider";
import SessionProvider from "@/components/provider/session-provider";
import ProgressbarProvider from "@/components/provider/progressbar-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const session = await validateRequest();
  const { user } = session;

  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      suppressContentEditableWarning={true}
    >
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <QueryProvider>
            <SessionProvider session={session}>
              <ProgressbarProvider>
                <main className="antialiased w-full">
                  {user ? (
                    <div className="flex w-full">
                      <LeftSidebar user={user} />
                      <div className="flex items-start justify-center w-full">
                        <div className="w-[340px]" />
                        {children}
                        {modal}
                        <div id="modal-root" />
                      </div>
                    </div>
                  ) : (
                    children
                  )}
                </main>
              </ProgressbarProvider>
            </SessionProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
